server:
  port: 0

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true # console 창
      settings:
        web-allow-others: true # 외부에서 접속 가능
      path: /h2-console #주소값
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.intanse_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-commerce.